defaults:
    - suite@_global_: adroit
    - override hydra/launcher: submitit_local

# environment
task: ???
discount: 0.99
img_size: 224
frame_stack: 2
action_repeat: 2
train_steps: 100000

# demonstrations
demos: 5

# planning
iterations: ???
num_samples: 512
num_elites: 64
mixture_coef: 0.05
min_std: 0.05
temperature: 0.5
momentum: 0.1

# learning
batch_size: 256
horizon: 5
reward_coef: 0.5
value_coef: 0.1
consistency_coef: 2
rho: 0.5
kappa: 0.1
lr: 3e-4
std_schedule: linear(0.1, ${min_std}, 12500)
horizon_schedule: linear(1, ${horizon}, 25000)
per: true
per_alpha: 0.6
per_beta: 0.4
grad_clip_norm: 10
seed_steps: 5000
update_freq: 2
tau: 0.01

# architecture
num_channels: 32
enc_dim: 256
mlp_dim: 512
latent_dim: 50

# wandb (required: fill in your details)
wandb_project: ???
wandb_entity: ???

# dirs (required: fill in your details)
logging_dir: .
demo_dir: ???

# misc
seed: 1
exp_name: default
eval_freq: 2000
eval_episodes: 30
save_freq: 20000
save_video: true
save_model: true

# convenience
domain: ???
task_title: ???
device: ???
obs_shape: ???
action_shape: ???
action_dim: ???
state_dim: ???
